name: GH Actions Cron Schedule
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare the environment
      run: |
        pip install -r requirements.txt

    - name: Check ota
      run: |
        for file in configs/config-*.yml; do python probe.py -c $file && echo "//"; done
